modelSummary:
  modelName: hawkesRNN
  modelVersion: 1
  developer: Biomedical Informatic Lab, College of Biomedical Engineering and Instrument Science, Zhejiang University
  literature: Huilong Duan, Zhoujian Sun, Wei Dong, Kunlun He and Zhengxing Huang*, On Clinical Event Prediction in Patient Treatment Trajectory Using Longitudinal Electronic Health Records. IEEE Journal of Biomedical and Health Informatics
  machineLearningFramework: Tensorflow
  machineLearningFrameworkVersion: 1.14

dataRange: fromStartToDesignatedVisit

# 直接要从数据库中获取的数据项
databaseRequest:
  - basicInfo
  - visitInfo
  - previousVisitInfo
  - medicine
  - operation
  - labTest
  - exam
  - vitalSign
  - diagnosis